"""The Android client, and the four ways it could quietly disagree with the console.

`mobile/` is a React Native app. Nothing in the Python suite can run it, and that is not what
these tests are for. They pin the properties that make it the same product rather than a
lookalike, each of which is a thing no compiler on either side can see.

* **The palette.** `mobile/src/theme.ts` cannot import a CSS custom property, so it holds nine
  hexes copied out of `apps/web/app/globals.css`. Copied values drift. Each one is annotated
  with the token it came from, and this file compares them.
* **The origin.** The client reads the deployed console's own data files. If `app.json` pointed
  at a different host from the one the console declares as its `metadataBase`, the phone would
  show one deployment's numbers under the other's name.
* **The trailing slash on `/api/live/`.** Measured from the console: the unslashed form is a
  308 and costs an extra round trip on a request that already takes tens of seconds. The
  comment in `apps/web/components/LiveConsole.tsx` records it, and the client has to agree.
* **The signing plugin.** `android/` is generated by `expo prebuild` and gitignored, so a
  hand-edited signing config lasts exactly until the next prebuild. The plugin that survives
  regeneration only runs if `app.json` lists it, and nothing else would notice if it stopped:
  the build would succeed and produce an APK signed with the public debug key.

The published key fingerprint is checked in both places it appears, because a release is
verified by comparing them and two copies of a value are one drift away from being useless.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MOBILE = REPO / "mobile"
THEME = MOBILE / "src" / "theme.ts"
API = MOBILE / "src" / "api.ts"
APP = MOBILE / "src" / "App.tsx"
APP_JSON = MOBILE / "app.json"
BUILD_SCRIPT = MOBILE / "build-apk.ps1"
MOBILE_README = MOBILE / "README.md"
GLOBALS_CSS = REPO / "apps" / "web" / "app" / "globals.css"
LAYOUT = REPO / "apps" / "web" / "app" / "layout.tsx"

#: A doc comment naming a stylesheet token, then the constant whose value it is.
#: `/** --ui-background: the ground ... */ ground: "#0c0e12",`
_THEME_ENTRY = re.compile(
    r"/\*\*\s*(--[a-z0-9-]+):[\s\S]*?\*/\s*(\w+):\s*\"(#[0-9a-fA-F]{6})\"",
)


def _css_tokens() -> dict[str, str]:
    """Every custom property the console's stylesheet sets, lowercased."""
    css = GLOBALS_CSS.read_text(encoding="utf-8")
    return {
        name: value.lower()
        for name, value in re.findall(r"(--[a-z0-9-]+):\s*(#[0-9a-fA-F]{6});", css)
    }


def _theme_entries() -> list[tuple[str, str, str]]:
    return [
        (token, name, value.lower())
        for token, name, value in _THEME_ENTRY.findall(THEME.read_text(encoding="utf-8"))
    ]


def test_the_client_palette_is_the_consoles_palette() -> None:
    entries = _theme_entries()
    assert len(entries) >= 9, f"only parsed {len(entries)} annotated colours from theme.ts"
    tokens = _css_tokens()
    wrong = [
        f"{name} is {value}, but {token} in globals.css is {tokens.get(token)}"
        for token, name, value in entries
        if tokens.get(token) != value
    ]
    assert not wrong, "; ".join(wrong)


def test_every_colour_in_the_client_theme_names_the_token_it_came_from() -> None:
    """An unannotated hex is one this file cannot check, so there may not be any."""
    source = THEME.read_text(encoding="utf-8")
    palette_block = source.split("export const palette", 1)[1].split("} as const", 1)[0]
    declared = set(re.findall(r"\"(#[0-9a-fA-F]{6})\"", palette_block))
    annotated = {value for _, _, value in _theme_entries()}
    assert declared == {v.lower() for v in annotated} or declared == annotated, (
        f"colours with no token comment: {sorted(declared - annotated)}"
    )


def test_the_client_and_the_console_point_at_one_deployment() -> None:
    origin = json.loads(APP_JSON.read_text(encoding="utf-8"))["expo"]["extra"]["origin"]
    layout = LAYOUT.read_text(encoding="utf-8")
    base = re.search(r"metadataBase:\s*new URL\(\"([^\"]+)\"\)", layout)
    assert base, "the console no longer declares a metadataBase"
    assert origin.rstrip("/") == base.group(1).rstrip("/"), (
        f"the client talks to {origin} and the console calls itself {base.group(1)}"
    )


def test_the_client_posts_to_the_slashed_endpoint() -> None:
    """The console measured the unslashed form as a 308. The client must not pay for it."""
    source = API.read_text(encoding="utf-8")
    assert "/api/live/`" in source, "the client posts to an endpoint that will redirect"
    assert '"POST"' in source


def test_the_three_screens_exist_and_are_all_reachable() -> None:
    screens = {
        path.stem for path in (MOBILE / "src" / "screens").glob("*.tsx")
    }
    assert screens == {"QueueScreen", "ObservationScreen", "LiveScreen"}, screens
    app = APP.read_text(encoding="utf-8")
    tabs = re.search(r"const TABS[\s\S]*?\];", app)
    assert tabs, "App.tsx no longer declares a TABS array"
    ids = set(re.findall(r"id:\s*\"(\w+)\"", tabs.group(0)))
    assert ids == {"queue", "observation", "live"}, ids
    for screen in screens:
        assert screen in app, f"{screen} is not rendered by App.tsx"


def test_the_signing_plugin_is_registered() -> None:
    """It only runs during prebuild if app.json lists it, and android/ is not tracked."""
    plugins = json.loads(APP_JSON.read_text(encoding="utf-8"))["expo"]["plugins"]
    assert "./plugins/with-release-signing.js" in plugins, plugins
    assert (MOBILE / "plugins" / "with-release-signing.js").is_file()


def test_the_published_fingerprint_agrees_with_itself() -> None:
    """Two copies of one value. A release is verified by comparing them."""
    script = BUILD_SCRIPT.read_text(encoding="utf-8")
    in_script = re.search(r'ExpectedFingerprint = "([0-9A-F]{64})"', script)
    assert in_script, "build-apk.ps1 no longer pins a fingerprint"
    readme = MOBILE_README.read_text(encoding="utf-8")
    colons = ":".join(
        in_script.group(1)[i : i + 2] for i in range(0, len(in_script.group(1)), 2)
    )
    assert in_script.group(1) in readme or colons in readme, (
        "mobile/README.md does not publish the fingerprint build-apk.ps1 checks against"
    )


def test_the_generated_android_project_is_not_tracked() -> None:
    """It is regenerated from app.json. Two sources for one project is the failure."""
    ignore = (MOBILE / ".gitignore").read_text(encoding="utf-8")
    for entry in ("android/", "node_modules/", "*.apk"):
        assert entry in ignore, f"mobile/.gitignore does not exclude {entry}"
