"""The published note receipt has to agree with the frozen drafts and with the console.

Three things can drift apart here and each one is invisible from the others. The frozen
drafts can stop matching the packets they were written from, because the console data is
regenerated by a different script. The receipt can stop matching the drafts, because it is
produced by a run that could have happened at any time. And the console's ``notes.json``
can stop matching the receipt, because it is a second file written in the same pass. So all
three are compared here rather than trusted.

Every check recomputes rather than reads. A receipt that asserts a refusal rate is only
evidence if the rate can be re-derived from the rows beside it, and the rows are only
evidence if the drafts they judge are the drafts the console shipped.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

from pipeline.tracetriage.explain import (
    adversarial_drafts,
    build_packet,
    control_drafts,
    prompt_contract_sha256,
    verify_note,
)

REPO = Path(__file__).resolve().parents[1]
_DATA = REPO / "apps" / "web" / "public" / "data"
_RECEIPT = REPO / "artifacts" / "EXPLAIN_RECEIPT.json"
_NOTES = _DATA / "notes.json"
_FIXTURE = REPO / "tests" / "fixtures" / "granite_notes.json"


def _load(path: Path) -> dict:
    if not path.exists():
        pytest.skip(f"{path.relative_to(REPO)} has not been generated")
    return json.loads(path.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def receipt() -> dict:
    return _load(_RECEIPT)


@pytest.fixture(scope="module")
def fixture() -> dict:
    return _load(_FIXTURE)


@pytest.fixture(scope="module")
def notes() -> dict:
    return _load(_NOTES)


@pytest.fixture(scope="module")
def packets():
    cards = json.loads((_DATA / "cards.json").read_text(encoding="utf-8"))["cards"]
    entries = json.loads((_DATA / "queue.json").read_text(encoding="utf-8"))["entries"]
    by_id = {int(e["obs_id"]): e for e in entries}
    return {
        int(c["obs_id"]): build_packet(c, by_id[int(c["obs_id"])])
        for c in cards
        if int(c["obs_id"]) in by_id
    }


# ---------------------------------------------------------------------------
# The frozen drafts
# ---------------------------------------------------------------------------


def test_the_frozen_prompt_contract_is_the_current_one(fixture):
    """A prompt edit without a re-freeze publishes answers to a different question."""
    assert fixture["generation"]["prompt_contract_sha256"] == prompt_contract_sha256(), (
        "the instruction text has changed since these drafts were frozen. Re-run "
        "scripts/run_explanations.py --freeze."
    )


def test_every_frozen_draft_matches_its_own_digest(fixture):
    for draft in fixture["drafts"]:
        actual = hashlib.sha256(draft["draft"].encode("utf-8")).hexdigest()
        assert actual == draft["draft_sha256"], f"observation {draft['obs_id']}"


def test_every_frozen_draft_still_matches_the_packet_it_was_written_from(
    fixture, packets
):
    """The case that would otherwise publish a sentence about superseded facts.

    The console data is regenerated by a different script. If a card's fields change, a
    frozen note is prose about numbers that are no longer on the page, and no type or
    schema can see it.
    """
    stale = []
    for draft in fixture["drafts"]:
        packet = packets.get(int(draft["obs_id"]))
        if packet is None:
            stale.append((draft["obs_id"], "no packet"))
        elif packet.sha256() != draft["packet_sha256"]:
            stale.append((draft["obs_id"], "packet changed"))
    assert not stale, (
        f"{stale}. The publisher retires these rather than judging them, so the receipt "
        f"stays honest, but a re-freeze is what actually fixes it."
    )


# ---------------------------------------------------------------------------
# The receipt, recomputed
# ---------------------------------------------------------------------------


def test_the_counts_add_up(receipt):
    counts = receipt["counts"]
    verdicts = [row["verdict"] for row in receipt["per_observation"]]
    assert counts["observations"] == len(verdicts)
    assert counts["emitted"] == verdicts.count("EMITTED")
    assert counts["refused"] == verdicts.count("REFUSED")
    assert counts["decided_by_the_checker"] == counts["emitted"] + counts["refused"]
    if counts["decided_by_the_checker"]:
        expected = round(counts["refused"] / counts["decided_by_the_checker"], 4)
        assert counts["refusal_rate"] == expected


def test_every_verdict_is_what_the_checker_says_today(receipt, fixture, packets):
    """The receipt is a claim about the checker's output, so run the checker."""
    frozen = {int(d["obs_id"]): d for d in fixture["drafts"]}
    checked = 0
    for row in receipt["per_observation"]:
        if row["verdict"] not in {"EMITTED", "REFUSED"}:
            continue
        draft = frozen[int(row["obs_id"])]["draft"]
        result = verify_note(draft, packets[int(row["obs_id"])])
        expected = "EMITTED" if result.ok else "REFUSED"
        assert row["verdict"] == expected, f"observation {row['obs_id']}"
        assert row.get("codes", []) == result.codes, f"observation {row['obs_id']}"
        checked += 1
    assert checked >= 10, f"only {checked} rows re-checked, so this proves little"


def test_the_checker_sensitivity_is_reproducible(receipt, packets):
    """Recomputed over every observation, and both halves have to survive.

    The receipt's headline used to be a refusal count over one observation. It is now the
    count of drafts refused for the reason they were built to trip, over all of them, so
    this recomputes exactly that: a checker that refused everything for a single reason
    would leave detection_rate below refusal_rate_over_adversarial and this would catch it.
    """
    sens = receipt["checker_sensitivity"]
    assert sens["observations_measured"] == len(packets)

    expected_fired = 0
    refused_at_all = 0
    adversarial = 0
    for packet in packets.values():
        for draft, expected in adversarial_drafts(packet):
            adversarial += 1
            result = verify_note(draft, packet)
            if result.ok:
                continue
            refused_at_all += 1
            if expected in result.codes:
                expected_fired += 1

    controls = 0
    refused_controls = 0
    for packet in packets.values():
        for draft in control_drafts(packet):
            controls += 1
            if not verify_note(draft, packet).ok:
                refused_controls += 1

    assert sens["adversarial_checks"] == adversarial
    assert sens["refused_for_any_reason"] == refused_at_all
    assert sens["caught_for_the_expected_reason"] == expected_fired
    assert sens["control_checks"] == controls
    assert sens["control_refused"] == refused_controls

    # A check is one draft against one packet, so the totals have to factorise. Without
    # this, "525" reads as the size of the adversarial suite, which is 21.
    assert sens["adversarial_checks"] == (
        sens["adversarial_drafts_per_observation"] * sens["observations_measured"]
    )
    assert sens["control_checks"] == (
        sens["control_drafts_per_observation"] * sens["observations_measured"]
    )
    assert sens["adversarial_drafts_per_observation"] == len(adversarial_drafts(packet))
    assert sens["control_drafts_per_observation"] == len(control_drafts(packet))
    assert sens["detection_rate"] == round(expected_fired / adversarial, 4)
    assert sens["refusal_rate_over_adversarial"] == round(refused_at_all / adversarial, 4)
    assert sens["false_refusal_rate"] == round(refused_controls / controls, 4)

    # Both directions have to be reported over a non-empty set. A receipt claiming a
    # perfect detection rate with no control set is the failure this pairing prevents.
    assert controls > 0
    assert adversarial > 0
    assert sens["detection_rate"] <= sens["refusal_rate_over_adversarial"], (
        "detection cannot exceed refusal: every draft caught for the right reason was "
        "refused, so the looser number is an upper bound on the stricter one"
    )


def test_the_stability_block_reports_what_it_measured(receipt):
    """A rate whose denominator is not the thing it says would be worse than no rate."""
    stability = receipt["run_to_run_stability"]
    across = stability["across_processes"]
    if not across.get("passes"):
        pytest.skip("no cross-process pass has been recorded yet")

    compared = sum(p["drafts_compared"] for p in across["passes"])
    differed = sum(p["drafts_that_differed"] for p in across["passes"])
    flips = sum(p["verdict_flips"] for p in across["passes"])
    assert across["drafts_compared"] == compared
    assert across["drafts_that_differed"] == differed
    assert across["verdict_flips"] == flips
    assert across["text_disagreement_rate"] == round(differed / compared, 4)
    assert across["verdict_flip_rate"] == round(flips / compared, 4)
    for record in across["passes"]:
        assert record["verdict_flips"] <= record["drafts_that_differed"], (
            "a verdict cannot flip in a draft that did not change"
        )


def test_the_frequency_finding_is_recomputable(receipt, packets):
    """The headline finding, re-derived from the rows rather than read from the summary.

    Two conditions, and both are re-applied here: within five percent of the observation's
    own receiver frequency in megahertz, and written in megahertz. The unit is read off the
    violation record. An earlier version of both the finding and this check used the numeric
    window alone, which counted any invented number that happened to land in the same range.
    """
    finding = receipt["hallucinated_downlink_frequency"]
    hits = 0
    in_range_wrong_unit = 0
    for row in receipt["per_observation"]:
        packet = packets.get(int(row["obs_id"]))
        if packet is None:
            continue
        true_mhz = packet.exact["receiver_frequency_hz"] / 1e6
        if not true_mhz:
            continue
        for violation in row.get("violations", []):
            if violation["code"] != "UNGROUNDED_NUMBER":
                continue
            assert "literal" in violation and "unit" in violation, (
                "an ungrounded-number violation has to carry its literal and unit "
                "structurally, or a consumer has to parse them back out of a message"
            )
            try:
                value = float(str(violation["literal"]).replace(",", ""))
            except ValueError:
                continue
            if abs(value - true_mhz) / true_mhz > 0.05:
                continue
            if violation["unit"] == "mhz":
                hits += 1
            else:
                in_range_wrong_unit += 1
    assert finding["occurrences"] == hits
    assert finding["in_range_but_not_written_as_a_frequency"] == in_range_wrong_unit
    assert finding["of_observations"] == len(receipt["per_observation"])


# ---------------------------------------------------------------------------
# The console's copy
# ---------------------------------------------------------------------------


def test_the_console_ships_the_note_the_receipt_describes(receipt, notes, fixture):
    by_id = {int(n["obs_id"]): n for n in notes["notes"]}
    frozen = {int(d["obs_id"]): d for d in fixture["drafts"]}
    for row in receipt["per_observation"]:
        obs_id = int(row["obs_id"])
        note = by_id[obs_id]
        assert note["source"] == row["shipped"], f"observation {obs_id}"
        if row["verdict"] == "EMITTED":
            assert note["note"] == frozen[obs_id]["draft"], f"observation {obs_id}"
            assert note["refused_codes"] == []
            assert note["why"] is None
        else:
            assert note["why"], f"observation {obs_id} ships a template with no reason"
        if row["verdict"] == "REFUSED":
            assert note["refused_codes"] == row["codes"], f"observation {obs_id}"


def test_the_console_names_the_model_that_wrote_the_notes(notes, fixture):
    assert notes["model"] == fixture["model"]
    assert notes["prompt_version"] == fixture["generation"]["prompt_version"]


# ---------------------------------------------------------------------------
# Idempotence
# ---------------------------------------------------------------------------


@pytest.mark.slow
def test_publishing_twice_produces_identical_bytes():
    """The receipt is committed, so a re-run that churns it breaks the freshness gate.

    Marked slow rather than skipped: it runs the publisher, which needs no model and no
    network, and it is the only check that the committed bytes are what the current code
    produces.
    """
    before = _RECEIPT.read_bytes() if _RECEIPT.exists() else None
    if before is None:
        pytest.skip("nothing published yet")
    notes_before = _NOTES.read_bytes()

    result = subprocess.run(
        [sys.executable, str(REPO / "scripts" / "run_explanations.py")],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert _RECEIPT.read_bytes() == before, "the receipt changed on a re-run"
    assert _NOTES.read_bytes() == notes_before, "notes.json changed on a re-run"


def test_the_receipt_carries_no_value_derived_from_the_current_commit(receipt, fixture):
    """The defect a clean clone found, and the reason the idempotence test above was weak.

    The receipt used to record HEAD's commit date. That does not churn between two runs at
    the same commit, which is what the field was reasoned about, and it churns on every
    commit after a publish, so the committed receipt disagreed with the publisher's output
    for every clone made later. A clone is always at a later commit than the publish, so a
    judge saw the failure and this machine did not.

    The invariant that replaces it: the receipt is a pure function of committed inputs, so
    any timestamp in it has to have come from the frozen fixture. Reinstating a stamp read
    from git turns this red as soon as one further commit exists.
    """
    fixture_text = json.dumps(fixture)
    stamps: list[tuple[str, str]] = []

    def walk(node: object, path: str) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                walk(value, f"{path}.{key}")
        elif isinstance(node, list):
            for i, value in enumerate(node):
                walk(value, f"{path}[{i}]")
        elif isinstance(node, str) and re.fullmatch(
            r"\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}.*", node
        ):
            stamps.append((path, node))

    walk(receipt, "receipt")
    foreign = [(path, value) for path, value in stamps if value not in fixture_text]
    assert not foreign, (
        f"these timestamps are in the receipt and not in the frozen fixture, so the "
        f"receipt depends on when it was run rather than on what it read: {foreign}"
    )
    assert stamps, "the receipt records no timestamp at all, so this proves nothing"
