/**
 * Write the narration the renderer speaks, and the captions the player shows.
 *
 * Both come out of `src/narration.ts`, which is a template over the same claims the
 * film draws, so this script has no numbers of its own. It resolves the receipts,
 * emits one JSON file naming every line with its beat, its frame window and the
 * receipt paths behind each figure, and emits a WebVTT track cut on the same
 * boundaries. `scripts/render_narration.py` reads the JSON and never reads a receipt,
 * which keeps exactly one place in this repository where a spoken figure is decided.
 *
 * Run: npm run narration
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { FPS } from "../src/theme";
import {
  LEAD_IN_SECONDS,
  NARRATED,
  TAIL_SECONDS,
  say,
  speechBudgetSeconds,
} from "../src/narration";

// fileURLToPath rather than new URL(...).pathname: this repository's path contains a
// space, and pathname hands back the percent-encoded form. Decoding it by hand is the
// kind of thing that works on the machine it was written on.
const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(HERE, "..", "narration");

type Cue = {
  beat: string;
  index: number;
  startFrame: number;
  endFrame: number;
  startSeconds: number;
  endSeconds: number;
  budgetSeconds: number;
  text: string;
  words: number;
  claims: { file: string; path: string; display: string; spoken: string }[];
};

let frame = 0;
const cues: Cue[] = NARRATED.map((beat, index) => {
  const startFrame = frame;
  frame += beat.durationInFrames;
  return {
    beat: beat.name,
    index,
    startFrame,
    endFrame: frame,
    startSeconds: startFrame / FPS,
    endSeconds: frame / FPS,
    budgetSeconds: Number(speechBudgetSeconds(beat).toFixed(3)),
    text: beat.line.text,
    words: beat.line.text.split(/\s+/).filter((w) => w.length > 0).length,
    // `display` is what the card draws and `spoken` is what the track says, both
    // derived from the same resolved value. The renderer's transcription check reads
    // `spoken`, so a figure the film spells out in words is checked as words.
    claims: beat.line.claims.map((claim) => ({
      file: claim.file,
      path: claim.path,
      display: claim.display,
      spoken: say(claim),
    })),
  };
});

const timestamp = (seconds: number): string => {
  const whole = Math.floor(seconds);
  const ms = Math.round((seconds - whole) * 1000);
  const h = Math.floor(whole / 3600);
  const m = Math.floor((whole % 3600) / 60);
  const s = whole % 60;
  const pad = (n: number, width = 2) => String(n).padStart(width, "0");
  return `${pad(h)}:${pad(m)}:${pad(s)}.${pad(ms, 3)}`;
};

mkdirSync(OUT_DIR, { recursive: true });

writeFileSync(
  join(OUT_DIR, "narration.json"),
  `${JSON.stringify(
    {
      note:
        "Generated by presentation/scripts/build-narration.ts from src/narration.ts. " +
        "Every figure here is resolved from a receipt; nothing in this file was typed.",
      fps: FPS,
      leadInSeconds: LEAD_IN_SECONDS,
      tailSeconds: TAIL_SECONDS,
      totalFrames: frame,
      cues,
    },
    null,
    2,
  )}\n`,
  "utf8",
);

const vtt = [
  "WEBVTT",
  "",
  ...cues.flatMap((cue) => [
    `${cue.beat}`,
    `${timestamp(cue.startSeconds + LEAD_IN_SECONDS)} --> ${timestamp(cue.endSeconds - TAIL_SECONDS)}`,
    cue.text,
    "",
  ]),
].join("\n");

writeFileSync(join(OUT_DIR, "narration.vtt"), vtt, "utf8");

const overBudget = cues.filter((cue) => cue.words / 2.6 > cue.budgetSeconds);
for (const cue of cues) {
  const estimate = cue.words / 2.6;
  const flag = estimate > cue.budgetSeconds ? "OVER" : "ok";
  console.log(
    `${cue.beat.padEnd(12)} ${String(cue.words).padStart(3)} words  ` +
      `budget ${cue.budgetSeconds.toFixed(1)}s  estimate ${estimate.toFixed(1)}s  ${flag}`,
  );
}
console.log(
  `\n${cues.length} cues, ${cues.reduce((n, c) => n + c.words, 0)} words, ` +
    `${(frame / FPS).toFixed(1)}s of film.`,
);
if (overBudget.length > 0) {
  console.log(
    `\n${overBudget.length} beat(s) estimated over budget. The estimate is words at ` +
      `2.6 a second; render_narration.py measures the real duration and is the check ` +
      `that counts.`,
  );
}
