/**
 * Six pre-registered gates and what each one came back as, on the first screen.
 *
 * The landing page had roughly a third of its opening viewport empty to the right
 * of the lede intro, and the most useful thing that could go there is the thing
 * this project is actually unusual for: six kill gates written down before any of
 * them was measured, reported at whatever they came back as. Two are met, three
 * came back inconclusive and one was never run, and a reader learns that in one
 * glance instead of scrolling to the table.
 *
 * Every row is read from `provenance.json`'s `gate_summary`, which is generated by
 * `scripts/sync_docs.py` from `docs/KILL_GATE.md` and the receipts. Nothing here is
 * typed, including the counts in the caption: `n_met` and `n_gates` come off the
 * same object, so a gate that changes verdict changes this strip and the /provenance
 * page together or neither.
 *
 * It also does a second job. The palette rule this console runs on is that grey is
 * measured and colour is computed, and the verdict markers are the clearest place a
 * reader meets the companion rule: state sits on the marker's form, not its hue.
 * Filled means decided, a hollow ring means measured and inconclusive, a dash means
 * no measurement exists. Six rows showing four of those in sequence teaches the
 * vocabulary before the reader reaches a table that depends on it.
 *
 * **No client JavaScript.** A server component. The stagger is a CSS
 * animation-delay per row set from the row index, and `prefers-reduced-motion:
 * reduce` lands every row at its final state, because the information is the
 * ledger and not the sweep.
 */
import Link from "next/link";

import { provenance } from "@/lib/data";
import { VerdictBadge } from "@/components/ui";

export default function GateLedger() {
  const summary = provenance.gate_summary;

  return (
    <aside className="ledger" aria-labelledby="ledger-title">
      <p className="ledger-title" id="ledger-title">
        Kill gates
        <span>
          written down before measuring, reported as they came back
        </span>
      </p>
      <ol className="ledger-rows">
        {summary.gates.map((gate, i) => (
          <li
            className="ledger-row"
            key={gate.gate}
            style={{ ["--row" as string]: String(i) }}
          >
            <span className="ledger-index num" aria-hidden="true">
              {String(gate.gate).padStart(2, "0")}
            </span>
            <span className="ledger-gate-title">{gate.title}</span>
            <VerdictBadge verdict={gate.verdict} />
          </li>
        ))}
      </ol>
      <p className="ledger-foot">
        <Link href="/evaluation/">
          {summary.n_met} of {summary.n_gates} met
        </Link>
        . Met means the threshold was cleared, so an inconclusive interval is not
        rounded into a pass.
      </p>
    </aside>
  );
}
