"""Draw the repository's own file tree into the README, from the tracked tree.

A hand-drawn tree is a picture of whatever the working directory looked like on the day
somebody typed it, and this repository's working directory holds a virtual environment,
a data snapshot, a render cache and 78 MB of evidence that is deliberately not committed.
A reader who clones this gets the tracked tree and nothing else, so the tree in the README
has to be the tracked tree or it is describing a checkout nobody has.

So this asks git rather than walking the filesystem. `git ls-files` is the definition:
if a path is not in it, a clone will not have it, and it does not belong in the picture.

Directories are summarised past a depth rather than listed to the leaf, because the point
of the tree is to tell a judge where to look, and five hundred paths tells them nothing. The count
beside a folded directory is the number of tracked files inside it, so the summary is a
measurement instead of an adjective.

    .venv/Scripts/python.exe scripts/sync_readme_tree.py           # rewrite the region
    .venv/Scripts/python.exe scripts/sync_readme_tree.py --check   # fail if it has drifted

Written between fences so the region is replaceable and the prose around it is not. The
`--check` mode is what the gate runs: it regenerates into memory and compares, so a file
added to the repository without re-running this is a failure rather than a stale diagram
nobody noticed.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
README = REPO / "README.md"

BEGIN = "<!-- generated by scripts/sync_readme_tree.py: file tree, do not edit -->"
END = "<!-- end file tree -->"

#: What each top-level entry is for. Keyed by tracked path; a path that appears in the
#: tree without a note here renders without one rather than inventing a description.
NOTE = {
    "apps/web": "the console, Next.js, statically exported to Vercel",
    "pipeline/tracetriage": "the measurement path: corridor fit, queue, baselines, grounding",
    "scripts": "one runnable step each, and the gate that ties them together",
    "artifacts": "the receipts every published figure is read out of",
    "tests": "the offline suite, including the checks that read the receipts back",
    "docs": "pre-registrations, the kill-gate log, and the build log",
    "contracts": "JSON Schemas the data plane is validated against",
    "flows": "LangFlow graphs, committed as files LangFlow wrote and can re-import",
    "mobile": "the Expo client",
    "api": "the two Python functions the live measurement runs on",
    ".bob": "what IBM Bob was pointed at",
}

#: Directories shown as a single folded line with their tracked file count. These hold
#: many files of one kind, and listing them would bury the entries a reader needs.
FOLD = {
    ".github",
    "api",
    "apps/web/app",
    "apps/web/audit",
    "apps/web/components",
    "apps/web/lib",
    "apps/web/public",
    "apps/web/tests",
    "artifacts",
    "contracts",
    "docs",
    "flows",
    "mobile",
    "pipeline/tracetriage",
    "scripts",
    "tests",
}

#: Build and tooling configuration. Real files, and a judge reading this tree to find the
#: measurement path does not need to walk past nine of them to reach it. They are still in
#: the repository; they are just not what the picture is for.
HIDE_SUFFIX = (
    ".gitignore", ".gitattributes", ".env.example", "-lock.json",
    "next-env.d.ts", "next.config.mjs", "eslint.config.mjs",
    "tsconfig.json", "vitest.config.ts",
    "package.json", "vercel.json", "pyproject.toml", "json.d.ts",
)


def all_tracked() -> list[str]:
    """Every tracked path, unfiltered. What a clone actually receives."""
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True
    )
    return [p for p in out.stdout.splitlines() if p]


def tracked() -> list[str]:
    """The paths the diagram shows: tracked, minus build and tooling configuration."""
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True
    )
    return sorted(
        p
        for p in out.stdout.splitlines()
        if p and not p.endswith(HIDE_SUFFIX)
    )


def build(paths: list[str], all_paths: list[str] | None = None) -> list[str]:
    """One line per shown entry, with folded directories collapsed to a count."""
    counts: dict[str, int] = {}
    for path in all_paths if all_paths is not None else paths:
        parts = path.split("/")
        for i in range(1, len(parts)):
            counts["/".join(parts[:i])] = counts.get("/".join(parts[:i]), 0) + 1

    shown: list[tuple[str, bool]] = []
    folded: set[str] = set()
    for path in paths:
        parent = next(
            (f for f in FOLD if path == f or path.startswith(f + "/")), None
        )
        if parent is not None:
            if parent not in folded:
                folded.add(parent)
                shown.append((parent, True))
            continue
        shown.append((path, False))

    # Insert the directories that survive folding, so the tree has branches to hang on.
    seen: set[str] = set()
    ordered: list[tuple[str, bool]] = []
    for path, is_folded in sorted(shown):
        parts = path.split("/")
        for i in range(1, len(parts)):
            branch = "/".join(parts[:i])
            if branch not in seen:
                seen.add(branch)
                ordered.append((branch, False))
        if path not in seen:
            seen.add(path)
            ordered.append((path, is_folded))

    lines: list[str] = ["tracetriage-august-2026/"]
    for path, is_folded in ordered:
        depth = path.count("/")
        name = path.split("/")[-1]
        is_dir = is_folded or any(p.startswith(path + "/") for p in paths)
        label = f"{name}/" if is_dir else name
        if is_folded:
            n = counts[path]
            label += f"   ({n} file{'' if n == 1 else 's'})"
        note = NOTE.get(path)
        row = f"{'  ' * depth}{label}"
        if note:
            row = f"{row:<46}{note}"
        lines.append(row.rstrip())
    return lines


def region(paths: list[str]) -> str:
    # Counted over every tracked path, including the ones HIDE_SUFFIX keeps out of the
    # picture. A folded directory's number is what a clone gets, so hiding a file from
    # the diagram must not quietly subtract it from the count beside the diagram.
    body = "\n".join(build(paths, all_tracked()))
    return f"{BEGIN}\n\n```\n{body}\n```\n\n{END}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"README.md has no file-tree region; add {BEGIN} and {END}", file=sys.stderr)
        return 2

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    fresh = head + region(tracked()) + tail

    if args.check:
        if fresh != text:
            print(
                "README.md file tree has drifted from the tracked tree. "
                "Run scripts/sync_readme_tree.py.",
                file=sys.stderr,
            )
            return 1
        print("README.md file tree matches the tracked tree.")
        return 0

    README.write_text(fresh, encoding="utf-8")
    print(f"wrote the file tree, {len(tracked())} tracked paths")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
