"""Regenerate the parts of docs/KILL_GATE.md that must agree with the receipts.

Two sections of that document are derived, not written: the status summary table at
the top, and the failure-log entries for the gates that have a receipt. Both had
carried numbers from an earlier run while the per-split table further down carried the
current ones, which is the claim drift this project audits other people's work for.

**This script must be idempotent, and the first version was not.** It replaced one
exact hardcoded string per row and asserted the string was present, so the second run
died on `AssertionError: gate 5 summary row not found`, while the document it was
supposed to maintain said in its own text that the sections "are now generated from
the receipt by scripts/sync_kill_gate.py, so the next re-run cannot leave them
behind". A one-shot fixup that cannot run twice is not a generator, and the Wave D
prompt was telling the next builder to re-run it after any pipeline re-run. It also
appended its own correction paragraph on every run, so a second run would have
duplicated it.

The rewrite anchors on structure rather than on the old content: the summary table is
whatever sits between the `## Status summary` heading and the next horizontal rule,
and each generated log entry is delimited by its own opening sentence and its closing
receipt reference. Running this on an already-synced file writes identical bytes.
`tests/test_kill_gate_sync.py` asserts that, and asserts each generated row against
its receipt, so this file cannot drift from the document again.

    .venv/Scripts/python.exe scripts/sync_kill_gate.py [--check]

`--check` writes nothing and exits 1 if the document is out of date, which is the form
`scripts/gate.py` and CI can call.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DOC = REPO / "docs/KILL_GATE.md"

STATUS_HEADING = "## Status summary\n"
RULE = "\n---\n"

GATE3_OPENER = "**2026-08-18, gate 3: NOT_ESTABLISHED.**"
GATE3_CLOSER = "Receipt: `artifacts/GATE3_RECEIPT.json`."
GATE6_OPENER = "**2026-08-18, gate 6: NOT ESTABLISHED.**"
GATE6_CLOSER = "Receipt: `artifacts/QUEUE_RECEIPT.json`."

# The per-split table was typed in C2 and never re-derived.
#
# By the time a review read it against the receipt it disagreed in eight cells across
# all four splits: cold_station's station and union upper bounds both read 3.896 where
# the receipt holds 3.859, chronological's union upper bound still read 1.755 after the
# bootstrap ceiling fix moved it to 1.740, and two n_decisive counts were gate 5's
# population rather than the queue's. The document that carries this table is the one
# the submission points at when it says a number cannot drift from its receipt, and
# `tests/test_claim_drift.py` compares scalar tokens rather than interval columns, so
# nothing went red. It is generated now.
PER_SPLIT_OPEN = (
    "<!-- generated by scripts/sync_kill_gate.py: per-split gate 6 table, do not edit -->"
)
PER_SPLIT_CLOSE = "<!-- end per-split gate 6 table -->"

# Gates 1, 2 and 4 have no receipt to read. Gates 1 and 2 were pre-measured with live
# probes before the snapshot existed and their evidence is the prose below the table;
# gate 4 was never run. They are literals here, and that is stated rather than hidden,
# because a literal that looks generated is worse than one that admits it is typed.
#: What each gate was asked, and the threshold it was asked against, both fixed before
#: any of them was measured. Named here rather than inside the row strings because
#: `scripts/sync_readme_results.py` prints the same six gates in the README and a second
#: copy of a threshold is a second thing to keep in step.
TITLES: dict[int, str] = {
    1: "Dataset volume and entity spread",
    2: "Metadata coverage for the corridor",
    3: "Corridor intersects a visible trace",
    4: "Blinded human decidability",
    5: "Physics beats image-only on Brier",
    6: "Queue lift over random",
}

THRESHOLDS: dict[int, str] = {
    1: "≥2,000 mature waterfalls, ≥12 transmitters, ≥30 stations",
    2: "≥80% of the sample computable",
    3: "≥70% of reviewed positives",
    4: "≥80% of a balanced sample decidable",
    5: "strict improvement, chronological split",
    6: "≥1.5x actionable conflicts at equal budget",
}

_STATIC_ROWS = {
    1: (
        f"| 1 | {TITLES[1]} | {THRESHOLDS[1]} | **PRE-PASSED on feasibility** |"
    ),
    2: (
        f"| 2 | {TITLES[2]} | {THRESHOLDS[2]} | **PRE-PASSED** |"
    ),
}

# Gate 4's row was a static literal reading **OPEN** while its receipt sat beside the
# others carrying NOT_RUN. Answering the worksheet would have moved the receipt and left
# this table saying OPEN, which is the drift this file exists to prevent for gates 3, 5
# and 6. The receipt's NOT_RUN renders as OPEN because that is the word this table has
# always used for it; every other verdict renders as itself, and one it has no wording
# for stops the sync instead of being published as OPEN.
_GATE4_WORDS = {
    "NOT_RUN": "**OPEN**",
    "PASSED": "**PASSED**",
    "FAILED": "**FAILED**",
    "NOT_ESTABLISHED": "**NOT ESTABLISHED**",
}


def _load(name: str) -> dict:
    return json.loads((REPO / "artifacts" / name).read_text(encoding="utf-8"))


def _n_discriminating(g3: dict) -> int:
    return sum(
        1 for o in g3["observations"] if o["null_calibration"]["discriminates"]
    )


def _n_nulls(g3: dict) -> int:
    """The null count the scored observations actually ran.

    Not-testable observations carry `n_nulls: 0` because they were never scored, so
    reading the first observation's value would publish 0 nulls for a gate that ran
    200. Take it from a scored one, and refuse to guess if they disagree.
    """
    counts = {
        o["null_calibration"]["n_nulls"]
        for o in g3["observations"]
        if o["null_calibration"]["p_value"] is not None
    }
    if len(counts) != 1:
        raise ValueError(f"scored observations disagree on n_nulls: {sorted(counts)}")
    return counts.pop()


def _gate3_row(g3: dict) -> str:
    grouping = g3["entity_grouping"]
    return (
        f"| 3 | {TITLES[3]} | {THRESHOLDS[3]} "
        f"| **{g3['verdict']}. {_n_discriminating(g3)}/"
        f"{g3['observations_scored']} testable discriminate "
        f"({g3['discriminating_rate'] * 100:.0f}%), but the exact one-sided 95% lower "
        f"bound on that rate is {g3['rate_lower_bound_95']:.3f}, so a "
        f"{g3['threshold'] * 100:.0f}% rate is not established. "
        f"{g3['observations_not_testable']} of {g3['observations_decisive']} not "
        f"testable; the {g3['observations_scored']} span "
        f"{grouping['distinct_stations']} stations on "
        f"{grouping['distinct_days']} night** |"
    )


def _narrow_arm_clause(brier: dict | None, aurc: dict | None) -> str:
    """What the narrower arm has established, read from its two corrected verdicts.

    This clause said "does clear zero and survives correction" as a literal until
    2026-08-19, when correcting over the 21 comparisons the ablation rule reads rather
    than the 7 on one split moved the Brier interval across zero while the risk-coverage
    interval stayed clear of it. A sentence that cannot express that outcome would have
    kept reporting the old one from a receipt that no longer said it.
    """
    def survives(comp: dict | None) -> bool | None:
        if not comp:
            return None
        return bool(comp.get("survives_correction")) and (
            comp.get("direction_adjusted", comp.get("direction")) == "challenger_better"
        )

    b, a = survives(brier), survives(aurc)
    family = (brier or aurc or {}).get("n_comparisons")
    over = f" over the {family} comparisons the ablation rule reads" if family else ""
    if b is None or a is None:
        return (
            "A narrower arm (image + corridor) leads on both metrics; its corrected "
            "intervals are in the receipt"
        )
    if b and a:
        return (
            "A narrower arm (image + corridor) clears zero on both Brier and "
            f"risk-coverage area and survives correction{over}"
        )
    if a and not b:
        return (
            "A narrower arm (image + corridor) leads on both metrics: its risk-coverage "
            f"margin survives correction{over} and its Brier margin does not"
        )
    if b and not a:
        return (
            "A narrower arm (image + corridor) leads on both metrics: its Brier margin "
            f"survives correction{over} and its risk-coverage margin does not"
        )
    return (
        "A narrower arm (image + corridor) leads on both metrics and neither margin "
        f"survives correction{over}"
    )


def _gate4_row() -> str:
    """Gate 4's row, from its receipt."""
    verdict = _load("GATE4_RECEIPT.json").get("verdict")
    if verdict not in _GATE4_WORDS:
        raise SystemExit(
            f"artifacts/GATE4_RECEIPT.json carries verdict {verdict!r}, and this table "
            f"has no wording for it. Known: {sorted(_GATE4_WORDS)}. A gate whose verdict "
            f"cannot be rendered has to stop the sync rather than be published as OPEN."
        )
    return f"| 4 | {TITLES[4]} | {THRESHOLDS[4]} | {_GATE4_WORDS[verdict]} |"


def _gate5_row(g5: dict, brier: dict | None, aurc: dict | None) -> str:
    return (
        f"| 5 | {TITLES[5]} | {THRESHOLDS[5]} "
        f"| **NOT ESTABLISHED. Margin +{g5['margin']:.5f}, 95% CI "
        f"{g5['ci95'][0]:+.5f} to {g5['ci95'][1]:+.5f} on {g5['n_observations']} test "
        f"observations across {g5['n_groups']} episodes, on the union of the "
        "episode-grouped and station-clustered intervals. "
        f"{_narrow_arm_clause(brier, aurc)}. The gate as worded does not pass.** |"
    )


def _gate6_row(chron: dict, station: dict, decisive: int) -> str:
    ci = chron["lift_ci95"]
    return (
        f"| 6 | {TITLES[6]} | {THRESHOLDS[6]} "
        f"| **NOT_ESTABLISHED. Point lift {chron['lift_point']:.3f}×, 95% "
        f"CI [{ci[0]:.3f}, {ci[1]:.3f}] on {decisive} decisive test observations "
        f"across {chron['n_groups']} episodes (chronological split, budget "
        f"{chron['n_queue_examined']}). The interval contains the 1.5× threshold; "
        f"cold_station PASSED at {station['lift_point']:.3f}×.** |"
    )


def _gate3_entry(g3: dict) -> str:
    n_scored = g3["observations_scored"]
    grouped = g3["entity_grouping"]
    nulls = _n_nulls(g3)
    return (
        f"{GATE3_OPENER} The expected corridor discriminates on every testable "
        f"observation: {_n_discriminating(g3)} of {n_scored}, each beating "
        f"{nulls} corridors built by permuting its own Doppler samples in time with "
        f"none reaching it (p = {1 / (nulls + 1):.3f}), and each beating all four "
        "scaled-swing controls that hold shape and smoothness fixed and vary only "
        "magnitude. The gate nonetheless does not pass, because it asks for a rate of "
        f"{g3['threshold'] * 100:.0f}% and a rate of "
        f"{g3['discriminating_rate']:.1f} on {n_scored} trials has an exact one-sided "
        f"95% Clopper-Pearson lower bound of {g3['rate_lower_bound_95']:.4f}, roughly "
        "half the threshold. Over the "
        f"{grouped['groups_scored']} independent {grouped['group_key']} groups the "
        f"bound is {grouped['grouped_rate_lower_bound_95']:.4f}. At a perfect rate "
        "the gate needs 9 of 9. This read PASSED until 2026-08-18 because "
        "`clears_threshold` compared the point estimate against the bar, and 1.0 "
        "≥ 0.70 is True for 1 of 1 as much as for 3 of 3. The per-observation "
        "evidence is unchanged and every sigma reproduced to six decimal places; only "
        f"the rate claim was withdrawn. {GATE3_CLOSER}"
    )


def _gate6_entry(receipt: dict, chron: dict, station: dict, decisive: int) -> str:
    ci = chron["lift_ci95"]
    st_ci = station["lift_ci95"]
    by_split = {s["split"]: s for s in receipt["per_split_summaries"]}
    return (
        f"{GATE6_OPENER} The review-value queue's point lift is "
        f"{chron['lift_point']:.3f}x over random at budget "
        f"{chron['n_queue_examined']} on the chronological split "
        f"({chron['n_queue_conflicts']} conflicts against "
        f"{chron['n_random_conflicts']:.1f} expected, {decisive} decisive test "
        f"observations across {chron['n_groups']} episodes). The 95% grouped bootstrap "
        f"interval is [{ci[0]:.3f}, {ci[1]:.3f}], which contains the 1.5x threshold, "
        "so the claim is not established. Bootstrap median "
        f"{chron['bootstrap_median']:.3f}. cold_station PASSED at "
        f"{station['lift_point']:.3f}x [{st_ci[0]:.3f}, {st_ci[1]:.3f}] on "
        f"{by_split['cold_station']['n_test_decisive']} decisive observations, which "
        "is the split where a reviewer meets unseen stations, and it does not "
        "substitute for the primary split. cold_transmitter "
        f"{receipt['gate6']['per_split']['cold_transmitter']['lift_point']:.3f}x and "
        "cold_combined "
        f"{receipt['gate6']['per_split']['cold_combined']['lift_point']:.3f}x are both "
        f"NOT_ESTABLISHED on intervals containing the threshold. {GATE6_CLOSER}"
    )


def _ci(pair: list[float] | None) -> str:
    """One interval, at the three decimals the rest of this document uses."""
    if not pair or any(v is None or v != v for v in pair):
        return "not measurable"
    return f"[{pair[0]:.3f}, {pair[1]:.3f}]"


def _per_split_table(queue: dict) -> str:
    """Gate 6's four splits, read from the receipt rather than remembered."""
    decisive = {s["split"]: s["n_test_decisive"] for s in queue["per_split_summaries"]}
    rows = [
        "| Split | Verdict | Point lift | Episode CI | Station CI "
        "| Governing (union) | n_decisive |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, split in queue["gate6"]["per_split"].items():
        if not split.get("measurable"):
            reason = split.get("not_measurable_reason") or "no reason recorded"
            rows.append(
                f"| {name} | NOT_MEASURABLE | | | | | {decisive.get(name, '')} |"
                f" <!-- {reason} -->"
            )
            continue
        rows.append(
            f"| {name} | {split['verdict']} | {split['lift_point']:.3f} "
            f"| {_ci(split.get('lift_ci95_episode'))} "
            f"| {_ci(split.get('lift_ci95_station'))} "
            f"| {_ci(split.get('lift_ci95'))} "
            f"| {decisive.get(name, '')} |"
        )
    return "\n".join(rows)


def _replace_between(text: str, opener: str, closer: str, new: str) -> str:
    """Swap the block that runs from `opener` to the end of `closer`, exactly once."""
    if text.count(opener) != 1:
        raise ValueError(f"expected exactly one {opener!r}, found {text.count(opener)}")
    start = text.index(opener)
    end = text.index(closer, start) + len(closer)
    return text[:start] + new + text[end:]


def render(text: str) -> str:
    """The document as the receipts say it should read. Pure, so a test can call it."""
    queue = _load("QUEUE_RECEIPT.json")
    fusion = _load("FUSION_RECEIPT.json")
    g3 = _load("GATE3_RECEIPT.json")

    chron = queue["gate6"]["per_split"]["chronological"]
    station = queue["gate6"]["per_split"]["cold_station"]
    g5 = fusion["gate5"]["per_split"]["chronological"]
    # The narrower arm's two corrected verdicts, from the split the gate is taken on.
    chron_split = next(
        (s for s in fusion["splits"] if s["split"] == "chronological"), {}
    )
    narrow_brier = (chron_split.get("multiplicity_adjusted") or {}).get(
        "image_corridor_vs_image_only"
    )
    narrow_aurc = (chron_split.get("selective") or {}).get(
        "aurc_shipped_vs_image_only"
    )
    # Gate 6's decisive count and gate 5's are different populations, and the document
    # had been quoting gate 5's 88 for both. Gate 6 runs on the queue, which
    # deduplicates 410 rows to 407, and one of the removed rows was decisive.
    decisive = {s["split"]: s for s in queue["per_split_summaries"]}["chronological"][
        "n_test_decisive"
    ]

    table = "\n".join(
        [
            "| # | Gate | Threshold | Status |",
            "|---|---|---|---|",
            _STATIC_ROWS[1],
            _STATIC_ROWS[2],
            _gate3_row(g3),
            _gate4_row(),
            _gate5_row(g5, narrow_brier, narrow_aurc),
            _gate6_row(chron, station, decisive),
        ]
    )

    # The summary table is whatever sits between the heading and the next rule.
    start = text.index(STATUS_HEADING) + len(STATUS_HEADING)
    end = text.index(RULE, start)
    text = text[:start] + "\n" + table + "\n" + text[end:]

    text = _replace_between(
        text, GATE6_OPENER, GATE6_CLOSER, _gate6_entry(queue, chron, station, decisive)
    )

    if PER_SPLIT_OPEN not in text or PER_SPLIT_CLOSE not in text:
        raise SystemExit(
            f"docs/KILL_GATE.md has no {PER_SPLIT_OPEN} ... {PER_SPLIT_CLOSE} region, "
            "so the per-split table has nowhere to go. Add the two comment markers "
            "around it."
        )
    text = _replace_between(
        text,
        PER_SPLIT_OPEN,
        PER_SPLIT_CLOSE,
        f"{PER_SPLIT_OPEN}\n{_per_split_table(queue)}\n{PER_SPLIT_CLOSE}",
    )

    gate3_entry = _gate3_entry(g3)
    if GATE3_OPENER in text:
        text = _replace_between(text, GATE3_OPENER, GATE3_CLOSER, gate3_entry)
    else:
        # A gate that changed verdict belongs in the failure log, above gate 6's entry
        # so the log stays in gate order.
        text = text.replace(GATE6_OPENER, gate3_entry + "\n\n" + GATE6_OPENER, 1)

    return text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if the document is out of date",
    )
    args = ap.parse_args()

    before = DOC.read_text(encoding="utf-8")
    after = render(before)

    if args.check:
        if before == after:
            print("KILL_GATE.md is in sync with the receipts")
            return 0
        print("KILL_GATE.md is OUT OF SYNC with the receipts; run without --check")
        return 1

    if before == after:
        print("KILL_GATE.md already in sync; nothing written")
        return 0
    DOC.write_text(after, encoding="utf-8")
    print("KILL_GATE.md synced to the receipts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
