"""Regenerate the parts of docs/KILL_GATE.md that must agree with the receipts.

Two sections of that document are derived, not written: the status summary table at
the top, and the failure-log entries for the gates that have a receipt. Both had
carried numbers from an earlier run while the per-split table further down carried the
current ones, which is the claim drift this project audits other people's work for.

**This script must be idempotent, and the first version was not.** It replaced one
exact hardcoded string per row and asserted the string was present, so the second run
died on `AssertionError: gate 5 summary row not found`, while the document it was
supposed to maintain said in its own text that the sections "are now generated from
the receipt by scripts/sync_kill_gate.py, so the next re-run cannot leave them
behind". A one-shot fixup that cannot run twice is not a generator, and the Wave D
prompt was telling the next builder to re-run it after any pipeline re-run. It also
appended its own correction paragraph on every run, so a second run would have
duplicated it.

The rewrite anchors on structure rather than on the old content: the summary table is
whatever sits between the `## Status summary` heading and the next horizontal rule,
and each generated log entry is delimited by its own opening sentence and its closing
receipt reference. Running this on an already-synced file writes identical bytes.
`tests/test_kill_gate_sync.py` asserts that, and asserts each generated row against
its receipt, so this file cannot drift from the document again.

    .venv/Scripts/python.exe scripts/sync_kill_gate.py [--check]

`--check` writes nothing and exits 1 if the document is out of date, which is the form
`scripts/gate.py` and CI can call.
"""

from __future__ import annotations

import argparse
import json
import math
import pathlib
import sys
from typing import Any

REPO = pathlib.Path(__file__).resolve().parent.parent
DOC = REPO / "docs/KILL_GATE.md"

STATUS_HEADING = "## Status summary\n"
RULE = "\n---\n"

GATE3_OPENER = "**2026-08-18, gate 3: NOT_ESTABLISHED.**"
GATE3_CLOSER = "Receipt: `artifacts/GATE3_RECEIPT.json`."
GATE6_OPENER = "**2026-08-18, gate 6: NOT ESTABLISHED.**"
GATE6_CLOSER = "Receipt: `artifacts/QUEUE_RECEIPT.json`."

# The per-split table was typed in C2 and never re-derived.
#
# By the time a review read it against the receipt it disagreed in eight cells across
# all four splits: cold_station's station and union upper bounds both read 3.896 where
# the receipt holds 3.859, chronological's union upper bound still read 1.755 after the
# bootstrap ceiling fix moved it to 1.740, and two n_decisive counts were gate 5's
# population rather than the queue's. The document that carries this table is the one
# the submission points at when it says a number cannot drift from its receipt, and
# `tests/test_claim_drift.py` compares scalar tokens rather than interval columns, so
# nothing went red. It is generated now.
PER_SPLIT_OPEN = (
    "<!-- generated by scripts/sync_kill_gate.py: per-split gate 6 table, do not edit -->"
)
PER_SPLIT_CLOSE = "<!-- end per-split gate 6 table -->"

GATE4_ARM_OPEN = (
    "<!-- generated by scripts/sync_kill_gate.py: gate 4 arm, do not edit -->"
)
GATE4_ARM_CLOSE = "<!-- end gate 4 arm -->"

# Gate 3's heading and its verdict paragraph both name the verdict word and the sample
# size, and both were typed. The heading read "NOT_ESTABLISHED on 3 testable
# observations" while the pool could only ever be three, and the paragraph restated the
# rate, both bounds and the n a perfect rate would need. `docs/E16_PREREGISTRATION.md`
# makes the pool growable, so every one of those numbers can move, on the one document
# this submission points at when it says a number cannot drift from its receipt.
GATE3_HEAD_OPEN = (
    "<!-- generated by scripts/sync_kill_gate.py: gate 3 heading, do not edit -->"
)
GATE3_HEAD_CLOSE = "<!-- end gate 3 heading -->"

GATE3_VERDICT_OPEN = (
    "<!-- generated by scripts/sync_kill_gate.py: gate 3 verdict, do not edit -->"
)
GATE3_VERDICT_CLOSE = "<!-- end gate 3 verdict -->"

# The two pools side by side. `docs/E16_PREREGISTRATION.md` section 5 commits to
# publishing pool A's five numbers beside pool B's, labelled corridor-selected, because
# the difference between them is the size of the selection effect the unit was built to
# measure. Publishing only the gate's own pool would leave that unanswerable.
GATE3_POOLS_OPEN = (
    "<!-- generated by scripts/sync_kill_gate.py: gate 3 pools, do not edit -->"
)
GATE3_POOLS_CLOSE = "<!-- end gate 3 pools -->"

# Gates 1 and 2 have no receipt to read: they were pre-measured with live probes before
# the snapshot existed and their evidence is the prose below the table. They are literals
# here, and that is stated rather than hidden, because a literal that looks generated is
# worse than one that admits it is typed. Gate 4 does have a receipt, and its row and its
# arm paragraph are both read from it.
#: What each gate was asked, and the threshold it was asked against, both fixed before
#: any of them was measured. Named here rather than inside the row strings because
#: `scripts/sync_readme_results.py` prints the same six gates in the README and a second
#: copy of a threshold is a second thing to keep in step.
TITLES: dict[int, str] = {
    1: "Dataset volume and entity spread",
    2: "Metadata coverage for the corridor",
    3: "Corridor intersects a visible trace",
    4: "Blinded human decidability",
    5: "Physics beats image-only on Brier",
    6: "Queue lift over random",
}

THRESHOLDS: dict[int, str] = {
    1: "≥2,000 mature waterfalls, ≥12 transmitters, ≥30 stations",
    2: "≥80% of the sample computable",
    3: "≥70% of reviewed positives",
    4: "≥80% of a balanced sample decidable",
    5: "strict improvement, chronological split",
    6: "≥1.5x actionable conflicts at equal budget",
}

_STATIC_ROWS = {
    1: (
        f"| 1 | {TITLES[1]} | {THRESHOLDS[1]} | **PRE-PASSED on feasibility** |"
    ),
    2: (
        f"| 2 | {TITLES[2]} | {THRESHOLDS[2]} | **PRE-PASSED** |"
    ),
}

# Gate 4's row was a static literal reading **OPEN** while its receipt sat beside the
# others carrying NOT_RUN. Answering the worksheet would have moved the receipt and left
# this table saying OPEN, which is the drift this file exists to prevent for gates 3, 5
# and 6. The receipt's NOT_RUN renders as OPEN because that is the word this table has
# always used for it; every other verdict renders as itself, and one it has no wording
# for stops the sync instead of being published as OPEN.
_GATE4_WORDS = {
    "NOT_RUN": "**OPEN**",
    "PASSED": "**PASSED**",
    "FAILED": "**FAILED**",
    "NOT_ESTABLISHED": "**NOT ESTABLISHED**",
}


def _load(name: str) -> dict:
    return json.loads((REPO / "artifacts" / name).read_text(encoding="utf-8"))


def _n_discriminating(g3: dict) -> int:
    return sum(
        1 for o in g3["observations"] if o["null_calibration"]["discriminates"]
    )


def _n_nulls(g3: dict) -> int:
    """The null count the scored observations actually ran.

    Not-testable observations carry `n_nulls: 0` because they were never scored, so
    reading the first observation's value would publish 0 nulls for a gate that ran
    200. Take it from a scored one, and refuse to guess if they disagree.
    """
    counts = {
        o["null_calibration"]["n_nulls"]
        for o in g3["observations"]
        if o["null_calibration"]["p_value"] is not None
    }
    if len(counts) != 1:
        raise ValueError(f"scored observations disagree on n_nulls: {sorted(counts)}")
    return counts.pop()


def _gate3_row(g3: dict) -> str:
    grouping = g3["entity_grouping"]
    return (
        f"| 3 | {TITLES[3]} | {THRESHOLDS[3]} "
        f"| **{g3['verdict']}. {_n_discriminating(g3)}/"
        f"{g3['observations_scored']} testable discriminate "
        f"({g3['discriminating_rate'] * 100:.0f}%), but the exact one-sided 95% lower "
        f"bound on that rate is {g3['rate_lower_bound_95']:.3f}, so a "
        f"{g3['threshold'] * 100:.0f}% rate is not established. "
        f"{g3['observations_not_testable']} of {g3['observations_decisive']} not "
        f"testable; the {g3['observations_scored']} span "
        f"{grouping['distinct_stations']} stations on "
        f"{grouping['distinct_days']} night** |"
    )


def _narrow_arm_clause(brier: dict | None, aurc: dict | None) -> str:
    """What the narrower arm has established, read from its two corrected verdicts.

    This clause said "does clear zero and survives correction" as a literal until
    2026-08-19, when correcting over the 21 comparisons the ablation rule reads rather
    than the 7 on one split moved the Brier interval across zero while the risk-coverage
    interval stayed clear of it. A sentence that cannot express that outcome would have
    kept reporting the old one from a receipt that no longer said it.
    """
    def survives(comp: dict | None) -> bool | None:
        if not comp:
            return None
        return bool(comp.get("survives_correction")) and (
            comp.get("direction_adjusted", comp.get("direction")) == "challenger_better"
        )

    b, a = survives(brier), survives(aurc)
    family = (brier or aurc or {}).get("n_comparisons")
    over = f" over the {family} comparisons the ablation rule reads" if family else ""
    if b is None or a is None:
        return (
            "A narrower arm (image + corridor) leads on both metrics; its corrected "
            "intervals are in the receipt"
        )
    if b and a:
        return (
            "A narrower arm (image + corridor) clears zero on both Brier and "
            f"risk-coverage area and survives correction{over}"
        )
    if a and not b:
        return (
            "A narrower arm (image + corridor) leads on both metrics: its risk-coverage "
            f"margin survives correction{over} and its Brier margin does not"
        )
    if b and not a:
        return (
            "A narrower arm (image + corridor) leads on both metrics: its Brier margin "
            f"survives correction{over} and its risk-coverage margin does not"
        )
    return (
        "A narrower arm (image + corridor) leads on both metrics and neither margin "
        f"survives correction{over}"
    )


def _gate4_row() -> str:
    """Gate 4's row, from its receipt."""
    verdict = _load("GATE4_RECEIPT.json").get("verdict")
    if verdict not in _GATE4_WORDS:
        raise SystemExit(
            f"artifacts/GATE4_RECEIPT.json carries verdict {verdict!r}, and this table "
            f"has no wording for it. Known: {sorted(_GATE4_WORDS)}. A gate whose verdict "
            f"cannot be rendered has to stop the sync rather than be published as OPEN."
        )
    return f"| 4 | {TITLES[4]} | {THRESHOLDS[4]} | {_GATE4_WORDS[verdict]} |"


def _gate5_row(g5: dict, brier: dict | None, aurc: dict | None) -> str:
    return (
        f"| 5 | {TITLES[5]} | {THRESHOLDS[5]} "
        f"| **NOT ESTABLISHED. Margin +{g5['margin']:.5f}, 95% CI "
        f"{g5['ci95'][0]:+.5f} to {g5['ci95'][1]:+.5f} on {g5['n_observations']} test "
        f"observations across {g5['n_groups']} episodes, on the union of the "
        "episode-grouped and station-clustered intervals. "
        f"{_narrow_arm_clause(brier, aurc)}. The gate as worded does not pass.** |"
    )


def _gate6_row(chron: dict, station: dict, decisive: int) -> str:
    ci = chron["lift_ci95"]
    return (
        f"| 6 | {TITLES[6]} | {THRESHOLDS[6]} "
        f"| **NOT_ESTABLISHED. Point lift {chron['lift_point']:.3f}×, 95% "
        f"CI [{ci[0]:.3f}, {ci[1]:.3f}] on {decisive} decisive test observations "
        f"across {chron['n_groups']} episodes (chronological split, budget "
        f"{chron['n_queue_examined']}). The interval contains the 1.5× threshold; "
        f"cold_station PASSED at {station['lift_point']:.3f}×.** |"
    )


def _smallest_perfect_n(threshold: float) -> int:
    """The first n whose perfect rate clears the bar, from the closed form at k = n.

    The exact one-sided Clopper-Pearson lower bound at k = n is ``alpha ** (1/n)``, so
    the smallest clearing n is ``ceil(log(alpha) / log(threshold))``. Published because
    "the gate is short of observations" is a claim and this is the number behind it.
    """
    return math.ceil(math.log(0.05) / math.log(threshold))


def _gate3_heading(g3: dict[str, Any]) -> str:
    """The section heading, which carries the verdict and the sample size."""
    n = g3["observations_testable"]
    noun = "observation" if n == 1 else "observations"
    return (
        f"## Gate 3: corridor intersects a visible trace, {g3['verdict']} on {n} "
        f"testable {noun}"
    )


def _gate3_verdict(g3: dict[str, Any]) -> str:
    """The verdict paragraph, derived from the receipt's own counts.

    Four branches, because "neither rate establishes the threshold" is only the right
    sentence while neither does. The version this replaced said exactly that under a
    heading that could not have said anything else.
    """
    verdict = g3["verdict"]
    threshold = g3["threshold"]
    bar = f"{threshold * 100:.0f}%"
    scored = g3["observations_scored"]
    rate = g3["discriminating_rate"]
    hits = round(rate * scored)
    bound = g3["rate_lower_bound_95"]

    grouping = g3["entity_grouping"]
    groups = grouping["groups_scored"]
    grouped_rate = grouping["grouped_discriminating_rate"] or 0.0
    grouped_hits = round(grouped_rate * groups)
    grouped_bound = grouping["grouped_rate_lower_bound_95"]
    grouped_clears = grouping["grouped_clears_threshold"]

    counts = (
        f"{hits} of {scored} testable observations discriminate ({rate * 100:.0f}%) "
        f"and {grouped_hits} of {groups} independent (station, date) "
        f"{'group does' if groups == 1 else 'groups do'}"
    )
    bounds = (
        f"The exact one-sided Clopper-Pearson 95% lower bound is `{bound:.4f}` over "
        f"observations and `{grouped_bound:.4f}` over groups"
    )

    if g3["clears_threshold"] and grouped_clears:
        return (
            f"**Gate 3 is {verdict}.** {counts}. {bounds}, and both clear the {bar} "
            f"threshold, which is what the gate asked for: the verdict follows the "
            f"interval and not the point estimate."
        )
    if g3["clears_threshold"]:
        return (
            f"**Gate 3 is {verdict}.** {counts}. {bounds}. The observation-level bound "
            f"clears the {bar} threshold and the grouped one does not, so the gate is "
            f"recorded as clearing on the weaker grouping only. The plan's rule is to "
            f"group, so this is reported rather than claimed as a pass."
        )
    if rate >= threshold:
        need = _smallest_perfect_n(threshold)
        shortfall = (
            f" A perfect rate would need {need} of {need} to clear {threshold:.2f}."
            if hits == scored
            else ""
        )
        return (
            f"**Gate 3 is {verdict}.** {counts}, and neither rate establishes the {bar} "
            f"threshold. {bounds}, so the data are consistent with a true intersection "
            f"rate well below the bar.{shortfall} The sample is what fails here, not the "
            f"measurements: the per-observation evidence is below and is unchanged by "
            f"this."
        )
    return (
        f"**Gate 3 is {verdict}.** {counts}, and the rate itself is below the {bar} "
        f"threshold before any interval is taken. {bounds}. This is not a sample-size "
        f"result: the corridor did not land on the trace often enough, on a pool fixed "
        f"in `docs/E16_PREREGISTRATION.md` before the run."
    )


def _load_optional(name: str) -> dict[str, Any] | None:
    """A receipt that may not exist yet, without turning its absence into a crash.

    The pool A comparison run is a separate invocation of `scripts/run_gate3.py`, so
    there is a window where the gate has an answer and the comparison does not. That
    window renders as "not run" rather than as a missing row.
    """
    path = REPO / "artifacts" / name
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _pool_row(label: str, r: dict[str, Any] | None, note: str) -> str:
    """One pool's five numbers, or an honest blank when that run has not happened."""
    if r is None:
        return f"| {label} | not run | | | | | {note} |"
    n = r["observations_scored"]
    rate = r["discriminating_rate"]
    hits = round(rate * n) if n else 0
    bound = r["rate_lower_bound_95"]
    return (
        f"| {label} | {n} | {hits} | {rate * 100:.0f}% | "
        f"{bound:.4f} | {r['verdict']} | {note} |"
    )


def _gate3_pools(g3: dict[str, Any], g3a: dict[str, Any] | None) -> str:
    """The two pools side by side, and what their difference means.

    Pool A is A3's own `UNCORRECTED` label, which is `sigma_curved - sigma_vertical >= 3`.
    Selecting on that and then testing whether the corridor discriminates measures the
    selection, so pool A cannot decide the gate and is here only as the comparison that
    shows how large that effect is.
    """
    threshold = g3["threshold"]
    # Which pool produced the published receipt is read off the receipt, never assumed.
    # This label was hardcoded to pool B, and against the A3 run actually in the tree it
    # announced a corridor-free pre-registered pool for observations the corridor chose,
    # which is the one substitution E16 exists to prevent.
    name = (g3.get("pool") or {}).get("name", "a3")
    labels = {
        "pool_b": ("**B, pre-registered**", "a corridor-free presence statistic"),
        "pool_a": ("A, corridor-selected", "A3's `UNCORRECTED` label, which reads the corridor"),
        "a3": ("A3's decisive set", "A3's verdict word, before E16 split the pools"),
    }
    main_label, main_note = labels.get(name, (f"`{name}`", "an unrecognised selector"))
    rows = [
        "| pool | scored | discriminating | rate | 95% lower bound | verdict | selected by |",
        "|---|---|---|---|---|---|---|",
        _pool_row(main_label, g3, main_note),
    ]
    if name != "pool_a":
        rows.append(
            _pool_row(
                "A, corridor-selected", g3a,
                "A3's `UNCORRECTED` label, which reads the corridor",
            )
        )
    if name == "a3":
        return "\n".join(rows) + "\n\n" + (
            "The published receipt is still A3's decisive set, chosen before "
            "`docs/E16_PREREGISTRATION.md` split the pools. Neither pre-registered pool "
            "has been scored yet, so there is no comparison to draw and this table says "
            "so rather than presenting one pool's rate as both."
        )
    tail = (
        f"Only pool B decides the gate, at a threshold of {threshold:.2f}. Pool A is "
        "selected on `sigma_curved - sigma_vertical >= 3`, so asking whether the corridor "
        "discriminates on it is asking whether the thing it was selected for is true of "
        "it. The two rates are published together because the gap between them is the "
        "size of that circularity, and a reader cannot judge it from one number."
    )
    if g3a is not None:
        gap = (g3a["discriminating_rate"] - g3["discriminating_rate"]) * 100
        tail += (
            f" Measured here it is {gap:+.0f} percentage points, on pools sharing "
            f"{g3.get('pool', {}).get('n_in_both', 'some')} observations."
        )
    return "\n".join(rows) + "\n\n" + tail


def _gate3_entry(g3: dict) -> str:
    n_scored = g3["observations_scored"]
    grouped = g3["entity_grouping"]
    nulls = _n_nulls(g3)
    return (
        f"{GATE3_OPENER} The expected corridor discriminates on every testable "
        f"observation: {_n_discriminating(g3)} of {n_scored}, each beating "
        f"{nulls} corridors built by permuting its own Doppler samples in time with "
        f"none reaching it (p = {1 / (nulls + 1):.3f}), and each beating all four "
        "scaled-swing controls that hold shape and smoothness fixed and vary only "
        "magnitude. The gate nonetheless does not pass, because it asks for a rate of "
        f"{g3['threshold'] * 100:.0f}% and a rate of "
        f"{g3['discriminating_rate']:.1f} on {n_scored} trials has an exact one-sided "
        f"95% Clopper-Pearson lower bound of {g3['rate_lower_bound_95']:.4f}, roughly "
        "half the threshold. Over the "
        f"{grouped['groups_scored']} independent {grouped['group_key']} groups the "
        f"bound is {grouped['grouped_rate_lower_bound_95']:.4f}. At a perfect rate "
        "the gate needs 9 of 9. This read PASSED until 2026-08-18 because "
        "`clears_threshold` compared the point estimate against the bar, and 1.0 "
        "≥ 0.70 is True for 1 of 1 as much as for 3 of 3. The per-observation "
        "evidence is unchanged and every sigma reproduced to six decimal places; only "
        f"the rate claim was withdrawn. {GATE3_CLOSER}"
    )


def _gate6_entry(receipt: dict, chron: dict, station: dict, decisive: int) -> str:
    ci = chron["lift_ci95"]
    st_ci = station["lift_ci95"]
    by_split = {s["split"]: s for s in receipt["per_split_summaries"]}
    return (
        f"{GATE6_OPENER} The review-value queue's point lift is "
        f"{chron['lift_point']:.3f}x over random at budget "
        f"{chron['n_queue_examined']} on the chronological split "
        f"({chron['n_queue_conflicts']} conflicts against "
        f"{chron['n_random_conflicts']:.1f} expected, {decisive} decisive test "
        f"observations across {chron['n_groups']} episodes). The 95% grouped bootstrap "
        f"interval is [{ci[0]:.3f}, {ci[1]:.3f}], which contains the 1.5x threshold, "
        "so the claim is not established. Bootstrap median "
        f"{chron['bootstrap_median']:.3f}. cold_station PASSED at "
        f"{station['lift_point']:.3f}x [{st_ci[0]:.3f}, {st_ci[1]:.3f}] on "
        f"{by_split['cold_station']['n_test_decisive']} decisive observations, which "
        "is the split where a reviewer meets unseen stations, and it does not "
        "substitute for the primary split. cold_transmitter "
        f"{receipt['gate6']['per_split']['cold_transmitter']['lift_point']:.3f}x and "
        "cold_combined "
        f"{receipt['gate6']['per_split']['cold_combined']['lift_point']:.3f}x are both "
        f"NOT_ESTABLISHED on intervals containing the threshold. {GATE6_CLOSER}"
    )


def _ci(pair: list[float] | None) -> str:
    """One interval, at the three decimals the rest of this document uses."""
    if not pair or any(v is None or v != v for v in pair):
        return "not measurable"
    return f"[{pair[0]:.3f}, {pair[1]:.3f}]"


def _per_split_table(queue: dict) -> str:
    """Gate 6's four splits, read from the receipt rather than remembered."""
    decisive = {s["split"]: s["n_test_decisive"] for s in queue["per_split_summaries"]}
    rows = [
        "| Split | Verdict | Point lift | Episode CI | Station CI "
        "| Governing (union) | n_decisive |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, split in queue["gate6"]["per_split"].items():
        if not split.get("measurable"):
            reason = split.get("not_measurable_reason") or "no reason recorded"
            rows.append(
                f"| {name} | NOT_MEASURABLE | | | | | {decisive.get(name, '')} |"
                f" <!-- {reason} -->"
            )
            continue
        rows.append(
            f"| {name} | {split['verdict']} | {split['lift_point']:.3f} "
            f"| {_ci(split.get('lift_ci95_episode'))} "
            f"| {_ci(split.get('lift_ci95_station'))} "
            f"| {_ci(split.get('lift_ci95'))} "
            f"| {decisive.get(name, '')} |"
        )
    return "\n".join(rows)


def _gate4_arm(receipt: dict) -> str:
    """The paragraph for a review that happened and does not answer the gate.

    Generated rather than written because it carries seven numbers. A hand-written version
    of this is the exact drift this file exists to prevent, and it would drift in the
    direction that flatters the project: an arm's rate reads like the gate's rate unless
    something keeps the two apart on every re-run.
    """
    arm = receipt.get("arm")
    if not arm:
        if (receipt.get("reviewer") or {}).get("kind") == "human":
            return _gate4_human(receipt)
        return (
            "No review has been recorded. The receipt carries "
            f"`{receipt.get('verdict')}` and no rate."
        )
    reviewer = arm["reviewer"]
    intra = arm["intra_rater"]
    axes = arm["network_label_agreement"]["by_axis"]
    seen, shape = axes["visible_signal"], axes["target_consistent"]
    return (
        f"**A review has been carried out and it does not answer this gate.** "
        f"{arm['decisive']} of {arm['observations_scored']} first-occurrence observations "
        f"were decidable, a rate of {arm['rate']:.4f}, exact one-sided 95% "
        f"[{arm['rate_lower_bound_95']:.4f}, {arm['rate_upper_bound_95']:.4f}] against the "
        f"0.80 threshold, with {intra['identical_on_all_three_axes']} of "
        f"{intra['repeated_pairs_scored']} repeated pairs answered identically on all three "
        f"axes. Agreement with the network's own label is "
        f"{seen['agreed_with_the_network_label']} of {seen['items_scored']} on the "
        f"visible-signal axis and {shape['agreed_with_the_network_label']} of "
        f"{shape['items_scored']} on the target-consistency axis, and neither of those is "
        f"the network's question: one counts a fixed local carrier as a signal, the other "
        f"wants a drifting curve and a packet burst near zero offset answers no to it. They "
        f"miss it in opposite directions, so both are published with their confusion "
        f"matrices and neither is named the right one. The reviewer was "
        f"**{reviewer['kind']}**, not a person: {reviewer['identity']} So the gate's own "
        f"verdict stays `{receipt['verdict']}` and this table still reads OPEN. What the arm "
        f"establishes is narrower than the gate and worth having on its own: the committed "
        f"sample supports a decisive judgment on the published instrument with every label "
        f"hidden, which was never measured before. What it cannot establish is whether a "
        f"person can do it, because the instrument the gate names is a person and this was "
        f"not one."
    )


def _gate4_human(receipt: dict) -> str:
    """The paragraph for the review the gate actually asks for.

    Generated for the same reason the arm paragraph is: it carries eight numbers, and a
    hand-written version would drift towards the flattering reading. It also has to say
    what the earlier model review becomes once a person has answered, because the two
    numbers invite being read as one and they are not: one is the gate, the other is a
    measurement of the sample that the gate does not ask for.
    """
    reviewer = receipt["reviewer"]
    intra = receipt["intra_rater"]
    axes = receipt["network_label_agreement"]["by_axis"]
    seen, shape = axes["visible_signal"], axes["target_consistent"]
    verdict = receipt["verdict"]
    settled = {
        "PASSED": "clears the 0.80 threshold, so the gate is met",
        "FAILED": (
            "sits below the 0.80 threshold, so the gate is not met and the finding is "
            "about the labelling protocol rather than about the model"
        ),
        "NOT_ESTABLISHED": (
            "contains the 0.80 threshold, so the gate is not met: a point estimate above "
            "the bar whose interval straddles it is published here as a failure, exactly "
            "as it is for gates 3, 5 and 6"
        ),
    }.get(verdict, "is reported as it came back")
    # A high decisive rate beside a low intra-rater rate is the one reading of this gate a
    # sceptical reader arrives at unaided, so it is stated here rather than left for them to
    # find. The two numbers answer different questions and the gap between them is a real
    # limit on what the gate established: that the plates can be judged, not that the
    # judgment is stable.
    intra_rate = intra["rate_identical_on_all_three_axes"]
    tension = ""
    if receipt["rate"] - intra_rate >= 0.15:
        tension = (
            f" Those two numbers should be read together and they are not the same claim. "
            f"Every plate supported a judgment, and on "
            f"{intra['repeated_pairs_scored'] - intra['identical_on_all_three_axes']} of "
            f"{intra['repeated_pairs_scored']} repeated plates the same reviewer reached a "
            f"different judgment the second time. Decidability at {receipt['rate']:.4f} is "
            f"what this gate asked for and what it establishes. Reliability at "
            f"{intra_rate:.4f} is a separate property, it is the weaker of the two, and no "
            f"claim here rests on it."
        )
    prior = receipt.get("prior_review")
    also = ""
    if prior:
        also = (
            f" A model answered the same committed sample before a person did, and that "
            f"review is kept in `prior_review` rather than deleted: "
            f"{prior['decisive']} of {prior['observations_scored']} decidable at "
            f"{prior['rate']:.4f}, by {prior['reviewer']['identity']} It is not this gate "
            f"and never was. What the two together allow, which neither allows alone, is a "
            f"comparison of a model reviewer against a person on identical blinded plates, "
            f"and it does not go the way a reader would guess: the model was less decisive "
            f"({prior['rate']:.4f} against {receipt['rate']:.4f}) and more self-consistent "
            f"({prior['intra_rater']['identical_on_all_three_axes']} of "
            f"{prior['intra_rater']['repeated_pairs_scored']} repeated pairs against "
            f"{intra['identical_on_all_three_axes']} of "
            f"{intra['repeated_pairs_scored']}). Neither arm is the other's control and "
            f"this is one reviewer of each kind, so it is published as an observation and "
            f"not as a result."
        )
    return (
        f"**A person has answered this worksheet and the gate is decided.** "
        f"{receipt['decisive']} of {receipt['observations_scored']} first-occurrence "
        f"observations were decidable, a rate of {receipt['rate']:.4f}, exact one-sided 95% "
        f"[{receipt['rate_lower_bound_95']:.4f}, {receipt['rate_upper_bound_95']:.4f}], "
        f"which {settled}. Intra-rater agreement is "
        f"{intra['identical_on_all_three_axes']} of {intra['repeated_pairs_scored']} "
        f"repeated pairs answered identically on all three axes, which bounds how far the "
        f"first number can be trusted. Agreement with the network's own label is "
        f"{seen['agreed_with_the_network_label']} of {seen['items_scored']} on the "
        f"visible-signal axis and {shape['agreed_with_the_network_label']} of "
        f"{shape['items_scored']} on the target-consistency axis, and neither of those is "
        f"the network's question.{tension} The reviewer was **{reviewer['kind']}**: "
        f"{reviewer['identity']} {reviewer['independence']}{also}"
    )


def _replace_between(text: str, opener: str, closer: str, new: str) -> str:
    """Swap the block that runs from `opener` to the end of `closer`, exactly once."""
    if text.count(opener) != 1:
        raise ValueError(f"expected exactly one {opener!r}, found {text.count(opener)}")
    start = text.index(opener)
    end = text.index(closer, start) + len(closer)
    return text[:start] + new + text[end:]


def render(text: str) -> str:
    """The document as the receipts say it should read. Pure, so a test can call it."""
    queue = _load("QUEUE_RECEIPT.json")
    fusion = _load("FUSION_RECEIPT.json")
    g3 = _load("GATE3_RECEIPT.json")
    g4 = _load("GATE4_RECEIPT.json")

    chron = queue["gate6"]["per_split"]["chronological"]
    station = queue["gate6"]["per_split"]["cold_station"]
    g5 = fusion["gate5"]["per_split"]["chronological"]
    # The narrower arm's two corrected verdicts, from the split the gate is taken on.
    chron_split = next(
        (s for s in fusion["splits"] if s["split"] == "chronological"), {}
    )
    narrow_brier = (chron_split.get("multiplicity_adjusted") or {}).get(
        "image_corridor_vs_image_only"
    )
    narrow_aurc = (chron_split.get("selective") or {}).get(
        "aurc_shipped_vs_image_only"
    )
    # Gate 6's decisive count and gate 5's are different populations, and the document
    # had been quoting gate 5's 88 for both. Gate 6 runs on the queue, which
    # deduplicates 410 rows to 407, and one of the removed rows was decisive.
    decisive = {s["split"]: s for s in queue["per_split_summaries"]}["chronological"][
        "n_test_decisive"
    ]

    table = "\n".join(
        [
            "| # | Gate | Threshold | Status |",
            "|---|---|---|---|",
            _STATIC_ROWS[1],
            _STATIC_ROWS[2],
            _gate3_row(g3),
            _gate4_row(),
            _gate5_row(g5, narrow_brier, narrow_aurc),
            _gate6_row(chron, station, decisive),
        ]
    )

    # The summary table is whatever sits between the heading and the next rule.
    start = text.index(STATUS_HEADING) + len(STATUS_HEADING)
    end = text.index(RULE, start)
    text = text[:start] + "\n" + table + "\n" + text[end:]

    text = _replace_between(
        text, GATE6_OPENER, GATE6_CLOSER, _gate6_entry(queue, chron, station, decisive)
    )

    if PER_SPLIT_OPEN not in text or PER_SPLIT_CLOSE not in text:
        raise SystemExit(
            f"docs/KILL_GATE.md has no {PER_SPLIT_OPEN} ... {PER_SPLIT_CLOSE} region, "
            "so the per-split table has nowhere to go. Add the two comment markers "
            "around it."
        )
    text = _replace_between(
        text,
        PER_SPLIT_OPEN,
        PER_SPLIT_CLOSE,
        f"{PER_SPLIT_OPEN}\n{_per_split_table(queue)}\n{PER_SPLIT_CLOSE}",
    )

    if GATE4_ARM_OPEN not in text or GATE4_ARM_CLOSE not in text:
        raise SystemExit(
            f"docs/KILL_GATE.md has no {GATE4_ARM_OPEN} ... {GATE4_ARM_CLOSE} region, so "
            "gate 4's arm paragraph has nowhere to go. Add the two comment markers around "
            "it. A gate whose numbers have no generated home is a gate whose numbers go "
            "stale by hand."
        )
    text = _replace_between(
        text,
        GATE4_ARM_OPEN,
        GATE4_ARM_CLOSE,
        f"{GATE4_ARM_OPEN}\n{_gate4_arm(g4)}\n{GATE4_ARM_CLOSE}",
    )

    for opener, closer, body, what in (
        (GATE3_HEAD_OPEN, GATE3_HEAD_CLOSE, _gate3_heading(g3), "gate 3's heading"),
        (GATE3_VERDICT_OPEN, GATE3_VERDICT_CLOSE, _gate3_verdict(g3), "gate 3's verdict"),
        (
            GATE3_POOLS_OPEN, GATE3_POOLS_CLOSE,
            _gate3_pools(g3, _load_optional("GATE3_POOL_A_RECEIPT.json")),
            "gate 3's pool comparison",
        ),
    ):
        if opener not in text or closer not in text:
            raise SystemExit(
                f"docs/KILL_GATE.md has no {opener} ... {closer} region, so {what} has "
                "nowhere to go. Add the two comment markers around it. A number whose "
                "only home is a typed line is a number that goes stale by hand."
            )
        text = _replace_between(text, opener, closer, f"{opener}\n{body}\n{closer}")

    gate3_entry = _gate3_entry(g3)
    if GATE3_OPENER in text:
        text = _replace_between(text, GATE3_OPENER, GATE3_CLOSER, gate3_entry)
    else:
        # A gate that changed verdict belongs in the failure log, above gate 6's entry
        # so the log stays in gate order.
        text = text.replace(GATE6_OPENER, gate3_entry + "\n\n" + GATE6_OPENER, 1)

    return text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if the document is out of date",
    )
    args = ap.parse_args()

    before = DOC.read_text(encoding="utf-8")
    after = render(before)

    if args.check:
        if before == after:
            print("KILL_GATE.md is in sync with the receipts")
            return 0
        print("KILL_GATE.md is OUT OF SYNC with the receipts; run without --check")
        return 1

    if before == after:
        print("KILL_GATE.md already in sync; nothing written")
        return 0
    DOC.write_text(after, encoding="utf-8", newline="\n")
    print("KILL_GATE.md synced to the receipts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
