"""Write the film's chapter list into the README, from the film's own beat durations.

The film is published as a link rather than committed, so the only thing the repository can
say about its shape is what the composition says. This reads `presentation/src/Film.tsx` and
`presentation/src/theme.ts` and turns the beat table into timestamps, in the format a video
description takes, so the chapter list cannot drift from the cut.

The titles below are this file's. Every one of them has to name a beat that exists, and
every beat has to have one, so renaming a beat fails here instead of leaving a chapter
pointing at a section of the film that is no longer there.

    .venv/Scripts/python.exe scripts/sync_film_chapters.py           # rewrite the region
    .venv/Scripts/python.exe scripts/sync_film_chapters.py --check   # fail if it has drifted

Written between fences so the region is replaceable and the prose around it is not. The
`--check` mode is what the gate runs: it regenerates into memory and compares.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
README = REPO / "README.md"
FILM = REPO / "presentation" / "src" / "Film.tsx"
THEME = REPO / "presentation" / "src" / "theme.ts"

BEGIN = "<!-- generated by scripts/sync_film_chapters.py: film chapters, do not edit -->"
END = "<!-- end film chapters -->"

#: Where the film is published. `None` until it is uploaded, and the region then carries no
#: watch link rather than a placeholder one: a badge pointing at nothing is worse than no
#: badge, and this is the only place the address is written down.
WATCH: str | None = None

#: What each beat is about, in the words an audience would use rather than the component
#: name. Keyed on the beat name in `Film.tsx`, and checked against it both ways.
TITLES = {
    "Hello": "One pass, one recording, and everything written about it",
    "Title": "What TraceTriage decides",
    "Problem": "Why most of the archive was never read",
    "Physics": "Measuring the Doppler offset instead of guessing it",
    "Queue": "Ordering the queue by review value",
    "Live": "A live take on the deployed console",
    "Flow": "The committed LangFlow run, and what it refused",
    "Session": "The grounding checker that decides what ships",
    "Result": "Six gates, with thresholds written down first",
    "Gates": "The point estimate and its interval",
    "Established": "The three results that came back decided",
    "Bob": "What IBM Bob built",
    "Colophon": "Receipts, licence and sources",
    "Thanks": "Close",
}

BEAT = re.compile(r'\{\s*name:\s*"(\w+)",\s*component:\s*\w+,\s*durationInFrames:\s*(\d+)\s*\}')


def fps() -> int:
    match = re.search(r"export const FPS\s*=\s*(\d+)", THEME.read_text(encoding="utf-8"))
    if match is None:
        raise SystemExit(f"no FPS in {THEME.relative_to(REPO)}")
    return int(match.group(1))


def beats() -> list[tuple[str, int]]:
    found = BEAT.findall(FILM.read_text(encoding="utf-8"))
    if not found:
        raise SystemExit(f"no beat table in {FILM.relative_to(REPO)}")
    names = {name for name, _ in found}
    if names != set(TITLES):
        missing = sorted(names - set(TITLES))
        extra = sorted(set(TITLES) - names)
        raise SystemExit(
            f"the chapter titles and the film's beats disagree. "
            f"no title for: {missing or 'none'}; no such beat: {extra or 'none'}"
        )
    return [(name, int(frames)) for name, frames in found]


def stamp(seconds: float) -> str:
    whole = int(seconds)
    return f"{whole // 60}:{whole % 60:02d}"


def region() -> str:
    rate = fps()
    table = beats()
    total = sum(frames for _, frames in table)
    lines = []
    running = 0
    for name, frames in table:
        lines.append(f"{stamp(running / rate)} {TITLES[name]}")
        running += frames
    body = "\n".join(lines)
    badge = (
        "[![Watch the film](https://img.shields.io/badge/watch-3%20min%2C%20narrated-"
        f"ff0000?style=flat-square&logo=youtube&logoColor=white)]({WATCH})\n\n"
        if WATCH
        else ""
    )
    return (
        f"{BEGIN}\n\n"
        f"{badge}"
        f"The cut runs {stamp(total / rate)} across {len(table)} beats, "
        f"under the challenge's three-minute cap.\n\n"
        f"```\n{body}\n```\n\n"
        f"{END}"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"README.md has no film-chapter region; add {BEGIN} and {END}", file=sys.stderr)
        return 1
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    fresh = head + region() + tail

    if args.check:
        if fresh != text:
            print(
                "README.md's chapter list is not what the film's beats produce. "
                "Run scripts/sync_film_chapters.py.",
                file=sys.stderr,
            )
            return 1
        print("README.md's chapter list matches the cut.")
        return 0

    README.write_text(fresh, encoding="utf-8")
    print(f"wrote the chapter list, {len(beats())} beats")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
